// Class automatically generated by Dev-C++ New Class wizard

#include "t.h" // class's header file

// class constructor
t::t()
{
	// insert your code here
}

// class destructor
t::~t()
{
	// insert your code here
}
