// Class automatically generated by Dev-C++ New Class wizard

#ifndef T_H
#define T_H

/*
 * No description
 */
class t
{
	public:
		// class constructor
		t();
		// class destructor
		~t();
};

#endif // T_H
